# Generated by Django 4.2 on 2023-04-21 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=500)),
                ('cookingtime', models.CharField(max_length=500)),
                ('instructions', djrichtextfield.models.RichTextField(max_length=10000)),
                ('ingredients', djrichtextfield.models.RichTextField(max_length=10000)),
                ('notes', djrichtextfield.models.RichTextField(blank=True, max_length=10000, null=True)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[400, None], upload_to='recipes/')),
                ('image_alt', models.CharField(max_length=100)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], default='breakfast', max_length=50)),
                ('cuisine_types', models.CharField(choices=[('african', 'African'), ('american', 'American'), ('caribbean', 'Caribbean'), ('asian', 'Asian'), ('middle_eastern', 'Middle Eastern'), ('chinese', 'Chinese'), ('indian', 'Indian'), ('pakistani', 'Pakistani'), ('indonesian', 'Indonesian'), ('european', 'European'), ('oceanic', 'Oceanic')], default='african', max_length=50)),
                ('calories', models.IntegerField()),
                ('posted_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posted_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', djrichtextfield.models.RichTextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recipe_connected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='recipes.recipe')),
            ],
        ),
    ]
